### ISSUE TITLE
准确率有问题

### ISSUE THREAD

**Issue by everysecon** [beeevita/EvoPrompt#10]
你好，首先感谢你们提供的开源项目。我在运行项目时发现了一个问题，在BBH中，尽管给出了很多示例都是the answer is结尾的，但是当我用gpt3.5turbo运行时模型的有些回答并没有answer is，导致评分严重降低，请问一下这个应该怎么解决，你们是否有同样的问题呢，感谢。

**Comment by beeevita** [comment]
> 你好，首先感谢你们提供的开源项目。我在运行项目时发现了一个问题，在BBH中，尽管给出了很多示例都是the answer is结尾的，但是当我用gpt3.5turbo运行时模型的有些回答并没有answer is，导致评分严重降低，请问一下这个应该怎么解决，你们是否有同样的问题呢，感谢。

我们在使用 davinci-003 的时候没有遇到过类似的问题，或许可以尝试以下两个方法：

- 调整 temperature=0
- 换成其他规范输出的格式，比如用 <answer></answer>
