### ISSUE TITLE
test time issue

### ISSUE THREAD

**Issue by Thedatababbler** [beeevita/EvoPrompt#11]
Thank you for your great job. 
When I run the run_de_alpaca.sh script. I choose the sst-5 dataset. However, during final evaluation in test files. I received the following error:
```
Traceback (most recent call last):
  File "/root/projects/prompt_tuning_with_constraint_ICLR/EvoPrompt/run.py", line 26, in <module>
    run(args)
  File "/root/projects/prompt_tuning_with_constraint_ICLR/EvoPrompt/run.py", line 20, in run
    de_evo(args=args, evaluator=evaluator)
  File "/root/projects/prompt_tuning_with_constraint_ICLR/EvoPrompt/evolution.py", line 18, in de_evo
    evoluter.evolute()
  File "/root/projects/prompt_tuning_with_constraint_ICLR/EvoPrompt/evoluter.py", line 653, in evolute
    best_score, best_prompt = evaluate_optimized_prompt(
  File "/root/projects/prompt_tuning_with_constraint_ICLR/EvoPrompt/infer.py", line 37, in evaluate_optimized_prompt
    eval_src, eval_tgt = load_cls_data(
  File "/root/projects/prompt_tuning_with_constraint_ICLR/EvoPrompt/utils.py", line 106, in load_cls_data
    raise ValueError
ValueError
```

I followed your instruction to download and decompressed the test file and put them under the data directory. However,  I found the test files are most csv files, which is different from the format of the dev files which are in txt format.  For example, in the test.csv file for sst-5, the lines in the testsets are as following:

> 1,"no movement , no yuks , not much of anything ."
> 0,"a gob of drivel so sickly sweet , even the eager consumers of moore 's pasteurized ditties will retch it up like rancid crème brûlée ."
> 2,` how many more voyages can this limping but dearly-loved franchise survive ? '
> 
But in the dev files, we have following format:

> you 'll gasp appalled and laugh outraged and possibly , watching the spectacle of a promising young lad treading desperately in a nasty sea , shed an errant tear .	3
manages to show life in all of its banality when the intention is quite the opposite .	1
the heavy-handed film is almost laughable as a consequence .	0

We can see that the labels position are quite different.  However, for both the infer script and training script, you use the same function in utils:
```python
def load_cls_data(verbalizers=None, data_path=None,  sample_indices=None):
    test_data = read_lines(
        data_path, sample_indices=sample_indices)
    test_src = []
    test_tgt = []
    for i, line in enumerate(test_data):
        
        try:
            cur_src, cur_tgt = line.split('\t')
        except:
            raise ValueError
        test_src.append(cur_src)
        test_tgt.append(verbalizers[int(cur_tgt)])
    return test_src, test_tgt
```
As you can see that, no matter the dev or test file formats, this function will return the label and src sentence in the same order this may incur errors. 

I manage to avoid the errors by modifying the 'process.py' file in each test file sub-directories to save the test file in tsv files and with [text,  label] order as following:
```python
ftest = open('./stsa.fine.test')
test = []
for line in ftest:
    line = line.strip()
    label = int(line[0])
    text = line[2:]
    test.append([text, label])
test = DataFrame(test)
test.to_csv('test2.tsv', header=False, index=False, sep='\t')
```
I just want to make sure this change of format will result in correct results and receive your confirmation.

**Comment by beeevita** [comment]
Yes I think there's no problem if you do such modifications. I preprocessed the test data to the same format as our dev files.
