### ISSUE TITLE
没有date_understanding.json

### ISSUE THREAD

**Issue by JingZed** [beeevita/EvoPrompt#4]
运行后提示FileNotFoundError: [Errno 2] No such file or directory: 'data/date_understanding.json'，文件里也没有找到文件

**Comment by JingZed** [comment]
运行命令是bash scripts/run_de_cot.sh

**Comment by JingZed** [comment]
对了，请问作者的机器配置是什么，我的12g显存没办法运行那个本地大模型，现在正在尝试用3.5 api

**Comment by beeevita** [comment]
BBH 的所有数据集在这里：https://github.com/FranxYao/chain-of-thought-hub/tree/main/BBH/data
我们在运行本地大模型用的是 alpaca-7b, 可以调整 batch size 减小显存
