### ISSUE TITLE
梯子问题

### ISSUE THREAD

**Issue by wertyhb-sns** [beeevita/EvoPrompt#6]
你好，我想请问一下，如果希望不挂梯子运行代码，使用Cloudflare，api_base的连接写成什么样子呀？https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY 谢谢您啦

**Comment by beeevita** [comment]
> 你好，我想请问一下，如果希望不挂梯子运行代码，使用Cloudflare，api_base的连接写成什么样子呀？https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY 谢谢您啦

这个链接我打不开
