### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by everysecon** [beeevita/EvoPrompt#9]
你好，感谢你们的项目，我想请问一下这个优化的原始prompt在哪里，我看的有点乱谢谢

**Comment by beeevita** [comment]
在` data/{task}/{dataset_name}/prompts.txt` 和 `data/{task}/{dataset_name}/prompts_auto.txt ` 里, 比如 `data/cls/agnews/prompts.txt`, `data/cls/agnews/prompts_auto.txt` 其中带有 auto 指的是用模型自动生成的
